// The roster. Every fighter has:
//  - stats: health, speed, jump, body size
//  - a passive "power" that is always on
//  - three moves: a primary attack (LMB) and two abilities (RMB/Q and E)
//
// Move `type`s are interpreted by server/abilities.js:
//   melee      — instant cone hit in front of the attacker
//   projectile — spawns one or more projectiles
//   dash       — lunge forward, hitting anything in the way
//   leap       — jump into the air; optional slam damage on landing, optional glide
//   shout      — cone of crowd control (stun/knockback)
//   buff       — heal / shield / speed boost on self

export const ANIMALS = {
  cow: {
    id: 'cow',
    name: 'Cow',
    title: 'Bessie the Bulwark',
    role: 'Tank',
    blurb: 'A walking wall of beef. Slow to start, impossible to stop.',
    color: '#f4f1ea',
    stats: { maxHp: 220, speed: 6.5, jump: 10, radius: 1.2, height: 2.1 },
    power: {
      name: 'Thick Hide',
      description: 'Takes 20% less damage from every source.',
      damageTakenMult: 0.8,
    },
    primary: {
      name: 'Headbutt',
      description: 'A heavy forward ram that sends enemies flying.',
      type: 'melee',
      cooldown: 0.85,
      range: 3.2,
      arc: 75,
      damage: 22,
      knockback: 11,
      lift: 5,
    },
    ability1: {
      name: 'Stampede',
      description: 'Charge forward, trampling everything in your path.',
      type: 'dash',
      cooldown: 7,
      speed: 24,
      duration: 0.65,
      damage: 30,
      knockback: 18,
      lift: 7,
    },
    ability2: {
      name: 'Fresh Milk',
      description: 'Chug a pail of milk: heal 55 HP and gain a light shield.',
      type: 'buff',
      cooldown: 13,
      heal: 55,
      shield: { mult: 0.7, duration: 3 },
    },
  },

  chicken: {
    id: 'chicken',
    name: 'Chicken',
    title: 'Cluck Norris',
    role: 'Skirmisher',
    blurb: 'Tiny, twitchy, and armed with an endless supply of eggs.',
    color: '#ffffff',
    stats: { maxHp: 90, speed: 9.5, jump: 12, radius: 0.55, height: 1.1 },
    power: {
      name: 'Wings (Technically)',
      description: 'Can double jump in mid-air.',
      airJumps: 1,
    },
    primary: {
      name: 'Egg Toss',
      description: 'Rapid-fire eggs. Low damage, high annoyance.',
      type: 'projectile',
      cooldown: 0.28,
      projectile: 'egg',
      speed: 42,
      damage: 10,
      gravity: 6,
      lifetime: 1.4,
      radius: 0.3,
      knockback: 3,
    },
    ability1: {
      name: 'Egg Bomb',
      description: 'Lob a volatile egg that explodes on impact.',
      type: 'projectile',
      cooldown: 6,
      projectile: 'bomb',
      speed: 24,
      damage: 0,
      gravity: 28,
      lifetime: 3,
      radius: 0.45,
      explode: { radius: 5, damage: 42, knockback: 16, lift: 8 },
    },
    ability2: {
      name: 'Flutter',
      description: 'Burst upward and glide gently back down.',
      type: 'leap',
      cooldown: 5,
      up: 15,
      forward: 6,
      glide: 2.2,
    },
  },

  pig: {
    id: 'pig',
    name: 'Pig',
    title: 'Hamm-er',
    role: 'Brawler',
    blurb: 'Rolls in mud, throws mud, lands on you like a sack of mud.',
    color: '#f7a8b8',
    stats: { maxHp: 165, speed: 7.5, jump: 10, radius: 0.95, height: 1.4 },
    power: {
      name: 'Mud Bath',
      description: 'Regenerates 6 HP/s after 3s without taking damage.',
      regen: { delay: 3, rate: 6 },
    },
    primary: {
      name: 'Mud Ball',
      description: 'A sticky glob of mud that slows whoever it hits.',
      type: 'projectile',
      cooldown: 0.55,
      projectile: 'mud',
      speed: 30,
      damage: 14,
      gravity: 10,
      lifetime: 1.5,
      radius: 0.4,
      knockback: 4,
      slow: { mult: 0.6, duration: 1.5 },
    },
    ability1: {
      name: 'Belly Flop',
      description: 'Launch into the air and crash down, crushing nearby foes.',
      type: 'leap',
      cooldown: 7,
      up: 14,
      forward: 8,
      slam: { radius: 6, damage: 36, knockback: 14, lift: 9 },
    },
    ability2: {
      name: 'Truffle Snack',
      description: 'Snack on a truffle to restore 45 HP.',
      type: 'buff',
      cooldown: 10,
      heal: 45,
    },
  },

  sheep: {
    id: 'sheep',
    name: 'Sheep',
    title: 'Baa-rbara',
    role: 'Controller',
    blurb: 'Soft on the outside. Deafening on the inside.',
    color: '#eeeeee',
    stats: { maxHp: 135, speed: 8, jump: 10.5, radius: 0.9, height: 1.4 },
    power: {
      name: 'Fluffy',
      description: 'All that wool halves incoming knockback.',
      knockbackTakenMult: 0.5,
    },
    primary: {
      name: 'Wool Burst',
      description: 'A short-range spray of three wool puffs.',
      type: 'projectile',
      cooldown: 0.7,
      projectile: 'wool',
      speed: 30,
      damage: 8,
      gravity: 0,
      lifetime: 0.45,
      radius: 0.45,
      knockback: 4,
      count: 3,
      spread: 14,
    },
    ability1: {
      name: 'Baa-rage',
      description: 'A deafening bleat that stuns everything in front of you.',
      type: 'shout',
      cooldown: 8,
      range: 10,
      arc: 70,
      damage: 12,
      knockback: 9,
      lift: 3,
      stun: 1.3,
    },
    ability2: {
      name: 'Wool Fortress',
      description: 'Puff up your fleece: take 60% less damage for 4s.',
      type: 'buff',
      cooldown: 12,
      shield: { mult: 0.4, duration: 4 },
    },
  },

  goat: {
    id: 'goat',
    name: 'Goat',
    title: 'Billy the Kid',
    role: 'Acrobat',
    blurb: 'Eats tin cans, climbs anything, fears nothing.',
    color: '#c9b79c',
    stats: { maxHp: 125, speed: 8.5, jump: 14, radius: 0.8, height: 1.5 },
    power: {
      name: 'Iron Stomach',
      description: 'Heals for 25% of the damage it deals.',
      lifesteal: 0.25,
    },
    primary: {
      name: 'Horn Ram',
      description: 'A quick horn jab with serious knockback.',
      type: 'melee',
      cooldown: 0.6,
      range: 2.8,
      arc: 60,
      damage: 17,
      knockback: 13,
      lift: 4,
    },
    ability1: {
      name: 'Mountain Leap',
      description: 'A huge forward leap that slams down on landing.',
      type: 'leap',
      cooldown: 6,
      up: 16,
      forward: 16,
      slam: { radius: 5, damage: 30, knockback: 12, lift: 7 },
    },
    ability2: {
      name: 'Tin Can Toss',
      description: 'Spit a half-eaten tin can at high speed.',
      type: 'projectile',
      cooldown: 3.2,
      projectile: 'can',
      speed: 40,
      damage: 25,
      gravity: 8,
      lifetime: 1.5,
      radius: 0.35,
      knockback: 8,
    },
  },

  horse: {
    id: 'horse',
    name: 'Horse',
    title: 'Neigh-poleon',
    role: 'Striker',
    blurb: 'The fastest thing on four legs, with hooves to match.',
    color: '#8b5a2b',
    stats: { maxHp: 150, speed: 10, jump: 11, radius: 1.1, height: 2.2 },
    power: {
      name: 'Kick Back',
      description: 'All attacks deal 50% more knockback.',
      knockbackDealtMult: 1.5,
    },
    primary: {
      name: 'Hoof Stomp',
      description: 'A powerful front-hoof strike.',
      type: 'melee',
      cooldown: 0.75,
      range: 3.3,
      arc: 55,
      damage: 20,
      knockback: 9,
      lift: 4,
    },
    ability1: {
      name: 'Gallop',
      description: 'Break into a full gallop: +70% speed for 3s.',
      type: 'buff',
      cooldown: 9,
      speedBoost: { mult: 1.7, duration: 3 },
    },
    ability2: {
      name: 'Horseshoe Hurl',
      description: 'Fling a horseshoe with pinpoint accuracy. Lucky for you, not them.',
      type: 'projectile',
      cooldown: 4,
      projectile: 'horseshoe',
      speed: 55,
      damage: 28,
      gravity: 2,
      lifetime: 1.2,
      radius: 0.35,
      knockback: 10,
    },
  },
};

export const ANIMAL_IDS = Object.keys(ANIMALS);
export const MOVE_SLOTS = ['primary', 'ability1', 'ability2'];

export function getAnimal(id) {
  return ANIMALS[id] || ANIMALS.cow;
}
